from __future__ import annotations


ALL_COMMANDS = {
    "init",
    "mode-init",
    "mode-status",
    "mode-switch",
    "work-unit-abort",
    "status",
    "audit",
    "show",
    "search",
    "closure",
    "context",
    "targets",
    "set-targets",
    "submit",
    "packet",
    "record-review",
    "admit",
    "revoke",
    "memory-add",
    "memory-update",
    "frontier",
    "adoption-plan",
    "plan-round",
    "round-status",
    "profile-closure-status",
    "profile-closure-record",
    "preflight-return",
    "validate-return",
    "ingest-return",
    "plan-repair-round",
    "make-verifier-task",
    "novelty-record",
    "novelty-status",
    "export-mermaid",
    "export-reader-html",
    "import-danus",
    "upgrade-workflow",
    "upgrade-project-copy",
    "claim-add",
    "claim-variant",
    "claim-show",
    "convention-add",
    "convention-show",
    "campaign-create",
    "campaign-activate",
    "campaign-update",
    "campaign-status",
    "campaign-target-add",
    "campaign-target-archive",
    "blackboard-type-register",
    "blackboard-space-create",
    "blackboard-node-add",
    "blackboard-edge-add",
    "blackboard-show",
    "blackboard-query",
    "blackboard-snapshot",
    "blackboard-snapshot-query",
    "blackboard-reindex",
    "blackboard-promote-node",
    "pulse-plan",
    "pulse-barrier",
    "pulse-void",
    "pulse-abort",
    "pulse-dispatch",
    "pulse-close",
    "pulse-status",
    "pulse-audit",
    "experiment-start",
    "experiment-event",
    "experiment-observe",
    "experiment-decision",
    "experiment-resume",
    "experiment-status",
    "experiment-finalize",
    "fact-bundle-submit",
    "make-bundle-verifier-task",
    "fact-bundle-verifier-task",
    "fact-bundle-record-review",
    "fact-bundle-admit",
    "export-claim-card",
    "lint-expert-document",
    "export-interpret-card",
    "lint-interpret-document",
    "paper-logic-init",
    "paper-logic-stage",
    "paper-logic-record-review",
    "paper-logic-freeze",
    "paper-logic-status",
    "paper-logic-show",
    "paper-logic-query",
    "paper-logic-link-exploration",
    "paper-logic-project-blackboard",
    "paper-logic-audit",
}
OPERATOR_COMMANDS = ALL_COMMANDS - {
    "preflight-return",
    "pulse-dispatch",
}


ROLE_COMMANDS = {
    "worker": {
        "show",
        "search",
        "closure",
        "context",
        "targets",
        "submit",
        "frontier",
        "preflight-return",
        "validate-return",
        "novelty-status",
        "experiment-start",
        "experiment-event",
        "experiment-resume",
        "experiment-status",
        "experiment-finalize",
    },
    "main": {
        "mode-status",
        "mode-switch",
        "work-unit-abort",
        "status",
        "audit",
        "show",
        "search",
        "closure",
        "context",
        "targets",
        "set-targets",
        "revoke",
        "memory-add",
        "memory-update",
        "frontier",
        "adoption-plan",
        "plan-round",
        "round-status",
        "profile-closure-status",
        "profile-closure-record",
        "validate-return",
        "ingest-return",
        "plan-repair-round",
        "make-verifier-task",
        "novelty-record",
        "novelty-status",
        "export-mermaid",
        "export-reader-html",
        "claim-add",
        "claim-variant",
        "claim-show",
        "convention-add",
        "convention-show",
        "campaign-create",
        "campaign-activate",
        "campaign-update",
        "campaign-status",
        "campaign-target-add",
        "campaign-target-archive",
        "blackboard-space-create",
        "blackboard-node-add",
        "blackboard-edge-add",
        "blackboard-show",
        "blackboard-query",
        "blackboard-snapshot",
        "blackboard-snapshot-query",
        "blackboard-reindex",
        "blackboard-promote-node",
        "pulse-plan",
        "pulse-barrier",
        "pulse-void",
        "pulse-abort",
        "pulse-close",
        "pulse-status",
        "pulse-audit",
        "experiment-start",
        "experiment-event",
        "experiment-observe",
        "experiment-decision",
        "experiment-resume",
        "experiment-status",
        "experiment-finalize",
        "make-bundle-verifier-task",
        "fact-bundle-verifier-task",
        "export-claim-card",
        "lint-expert-document",
        "export-interpret-card",
        "lint-interpret-document",
        "paper-logic-init",
        "paper-logic-stage",
        "paper-logic-freeze",
        "paper-logic-status",
        "paper-logic-show",
        "paper-logic-query",
        "paper-logic-link-exploration",
        "paper-logic-project-blackboard",
        "paper-logic-audit",
    },
    # The cooperative host adapter alone attests that a real clean-context
    # subagent dispatch occurred. Workers cannot self-report this receipt.
    "host": {
        "pulse-dispatch",
        "pulse-status",
        "pulse-audit",
    },
    # Verifiers are deliberately not project-shell users.  The orchestrator
    # gives each fresh verifier one frozen packet and one review return path.
    "verifier": set(),
    "gateway": {
        "mode-status",
        "status",
        "audit",
        "profile-closure-status",
        "record-review",
        "admit",
        "revoke",
        "novelty-status",
        "fact-bundle-record-review",
        "fact-bundle-admit",
    },
    # Paper auditors can inspect exact frozen/staged paper evidence and append
    # one independent review. They receive no blackboard, memory, fact, or
    # admission mutation capability.
    "paper-auditor": {
        "paper-logic-record-review",
        "paper-logic-status",
        "paper-logic-show",
        "paper-logic-query",
        "paper-logic-audit",
    },
    "operator": OPERATOR_COMMANDS,
}

KNOWN_ROLES = tuple(sorted(ROLE_COMMANDS))
V4_WORKER_COMMANDS = {
    "preflight-return",
    "validate-return",
    "experiment-start",
    "experiment-event",
    "experiment-resume",
    "experiment-status",
    "experiment-finalize",
}
V4_BOUND_WORKER_QUERY_COMMANDS = {
    "claim-show",
    "convention-show",
    "campaign-status",
    "blackboard-show",
    "blackboard-snapshot-query",
}


def allowed_commands(role: str) -> set[str]:
    # Fail closed: an unknown role gets no project capability.
    return set(ROLE_COMMANDS.get(role, set()))


def allowed_commands_for_workflow(
    role: str,
    workflow_evidence_version: int,
) -> set[str]:
    commands = allowed_commands(role)
    if role == "worker" and workflow_evidence_version >= 4:
        return commands.intersection(V4_WORKER_COMMANDS)
    return commands


def allowed_bound_worker_queries_for_workflow(
    role: str,
    workflow_evidence_version: int,
) -> set[str]:
    """Return exact-id queries that require a separately validated task card."""

    if role == "worker" and workflow_evidence_version >= 4:
        return set(V4_BOUND_WORKER_QUERY_COMMANDS)
    return set()
